const classes = [
	{
		id: 1,
		name: "Fighter",
		stats: {
			str: 14,
			dex: 12,
			con: 16,
			int: 8,
			wis: 8,
			cha: 12,
		},
		hitDice: 10,
		proficiencies: [
			"Light Armor",
			"Medium Armor",
			"Heavy Armor",
			"Shields",
			"Simple Weapons",
			"Martial Weapons",
		],
		primaryAbility: "Constitution",
		savingThrows: ["Strength", "Constitution"],
	},
	{
		id: 2,
		name: "Barbarian",
		stats: {
			str: 17,
			dex: 11,
			con: 16,
			int: 8,
			wis: 10,
			cha: 10,
		},
		hitDice: 12,
		proficiencies: [
			"Light Armor",
			"Medium Armor",
			"Shields",
			"Simple Weapons",
			"Martial Weapons",
		],
		primaryAbility: "Strength",
		savingThrows: ["Strength", "Constitution"],
	},
	{
		id: 3,
		name: "Rogue",
		stats: {
			str: 10,
			dex: 16,
			con: 12,
			int: 12,
			wis: 8,
			cha: 14,
		},
		hitDice: 8,
		proficiencies: ["Light Armor", "Simple Weapons", "Crossbows", "Bows"],
		primaryAbility: "Dexterity",
		savingThrows: ["Dexterity", "Charisma"],
	},
	{
		id: 4,
		name: "Wizard",
		stats: {
			str: 8,
			dex: 12,
			con: 14,
			int: 16,
			wis: 12,
			cha: 10,
		},
		hitDice: 6,
		proficiencies: ["Simple Weapons", "Quarterstaffs"],
		primaryAbility: "Intelligence",
		savingThrows: ["Intelligence", "Constitution"],
	},
	{
		id: 5,
		name: "Bard",
		stats: {
			str: 8,
			dex: 14,
			con: 12,
			int: 10,
			wis: 12,
			cha: 16,
		},
		hitDice: 8,
		proficiencies: ["Light Armor", "Simple Weapons", "Instruments"],
		primaryAbility: "Charisma",
		savingThrows: ["Dexterity", "Charisma"],
	},
	{
		id: 6,
		name: "Cleric",
		stats: {
			str: 12,
			dex: 10,
			con: 14,
			int: 8,
			wis: 16,
			cha: 12,
		},
		hitDice: 8,
		proficiencies: ["Light Armor", "Medium Armor", "Shields", "Simple Weapons"],
		primaryAbility: "Wisdom",
		savingThrows: ["Wisdom", "Constitution"],
	},
];

module.exports = classes;
