const weapons = [
	{
		id: 1,
		name: "Dagger",
		type: "Simple",
		damage: "1d4",
		damageType: "Piercing",
		modifier: "Dexterity",
		properties: ["Finesse", "Light", "Thrown"],
	},
	{
		id: 2,
		name: "Shortsword",
		type: "Simple",
		damage: "1d6",
		damageType: "Piercing",
		modifier: "Dexterity",
		properties: ["Finesse", "Light"],
	},
	{
		id: 3,
		name: "Longsword",
		type: "Martial",
		damage: "1d8",
		damageType: "Slashing",
		modifier: "Strength",
		properties: ["Versatile"],
	},
	{
		id: 4,
		name: "Greatsword",
		type: "Martial",
		damage: "2d6",
		damageType: "Slashing",
		modifier: "Strength",
		properties: ["Heavy", "Two-Handed"],
	},
	{
		id: 5,
		name: "Greataxe",
		type: "Martial",
		damage: "1d12",
		damageType: "Slashing",
		modifier: "Strength",
		properties: ["Heavy", "Two-Handed"],
	},
	{
		id: 6,
		name: "Shortbow",
		type: "Bows",
		damage: "1d6",
		damageType: "Piercing",
		modifier: "Dexterity",
		properties: ["Ammunition", "Two-Handed"],
	},
	{
		id: 7,
		name: "Longbow",
		type: "Bows",
		damage: "1d8",
		damageType: "Piercing",
		modifier: "Dexterity",
		properties: ["Ammunition", "Heavy", "Two-Handed"],
	},
	{
		id: 8,
		name: "Crossbow",
		type: "Crossbows",
		damage: "1d8",
		damageType: "Piercing",
		modifier: "Strength",
		properties: ["Ammunition", "Heavy", "Two-Handed"],
	},
	{
		id: 9,
		name: "Rapier",
		type: "Martial",
		damage: "1d8",
		damageType: "Piercing",
		modifier: "Dexterity",
		properties: ["Finesse"],
	},
	{
		id: 10,
		name: "Maul",
		type: "Martial",
		damage: "2d6",
		damageType: "Bludgeoning",
		modifier: "Strength",
		properties: ["Heavy", "Two-Handed"],
	},
	{
		id: 11,
		name: "Warhammer",
		type: "Martial",
		damage: "1d8",
		damageType: "Bludgeoning",
		modifier: "Strength",
		properties: ["Versatile"],
	},
	{
		id: 12,
		name: "Club",
		type: "Simple",
		damage: "1d4",
		damageType: "Bludgeoning",
		modifier: "Strength",
		properties: ["Light"],
	},
	{
		id: 13,
		name: "Great Club",
		type: "Simple",
		damage: "1d8",
		damageType: "Bludgeoning",
		modifier: "Strength",
		properties: ["Two-Handed"],
	},
	{
		id: 14,
		name: "Handaxe",
		type: "Simple",
		damage: "1d6",
		damageType: "Slashing",
		modifier: "Desxterity",
		properties: ["Light", "Thrown"],
	},
	{
		id: 15,
		name: "Javelin",
		type: "Simple",
		damage: "1d6",
		damageType: "Piercing",
		modifier: "Dexterity",
		properties: ["Thrown"],
	},
	{
		id: 16,
		name: "Spear",
		type: "Simple",
		damage: "1d6",
		damageType: "Piercing",
		modifier: "Dexterity",
		properties: ["Thrown", "Versatile"],
	},
	{
		id: 17,
		name: "Sickle",
		type: "Simple",
		damage: "1d4",
		damageType: "Slashing",
		modifier: "Dexterity",
		properties: ["Light"],
	},
	{
		id: 18,
		name: "Flail",
		type: "Martial",
		damage: "1d8",
		damageType: "Bludgeoning",
		modifier: "Strength",
		properties: [],
	},
	{
		id: 19,
		name: "Halberd",
		type: "Martial",
		damage: "1d10",
		damageType: "Slashing",
		modifier: "Strength",
		properties: ["Heavy", "Two-Handed"],
	},
	{
		id: 20,
		name: "Glaive",
		type: "Martial",
		damage: "1d10",
		damageType: "Slashing",
		modifier: "Strength",
		properties: ["Heavy", "Two-Handed"],
	},
	{
		id: 21,
		name: "Pike",
		type: "Martial",
		damage: "1d10",
		damageType: "Piercing",
		modifier: "Dexterity",
		properties: ["Heavy", "Two-Handed"],
	},
	{
		id: 22,
		name: "Morningstar",
		type: "Martial",
		damage: "1d8",
		damageType: "Piercing",
		modifier: "Strength",
		properties: [],
	},
	{
		id: 23,
		name: "Whip",
		type: "Martial",
		damage: "1d4",
		damageType: "Slashing",
		modifier: "Dexterity",
		properties: ["Finesse"],
	},
	{
		id: 24,
		name: "Quarterstaff",
		type: "Quarterstaffs",
		damage: "1d6",
		damageType: "Bludgeoning",
		modifier: "Strength",
		properties: ["Versatile"],
	},
	{
		id: 25,
		name: "Trident",
		type: "Martial",
		damage: "1d6",
		damageType: "Piercing",
		modifier: "Strength",
		properties: ["Thrown", "Versatile"],
	},
];

module.exports = weapons;
